name: 'FedRAMP KSI Evidence'
description: 'Evaluate Terraform configuration for FedRAMP 20x KSI compliance (MLA-05, CNA-01) and generate evidence packs'
author: 'FedRAMP KSI Team'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  root_paths:
    description: 'Comma-separated list of paths to scan for Terraform files'
    required: false
    default: '.'
  ksi_id:
    description: 'KSI identifier (fixed to KSI-MLA-05 for this action)'
    required: false
    default: 'KSI-MLA-05'
  artifact_prefix:
    description: 'Prefix for the evidence artifact name'
    required: false
    default: 'evidence_ksi-mla-05'
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  terraform_version:
    description: 'Terraform version to install (leave empty to use pre-installed)'
    required: false
    default: ''

outputs:
  # MLA-05 outputs
  status:
    description: 'KSI-MLA-05 status: PASS, FAIL, or ERROR'
    value: ${{ steps.evaluate.outputs.status }}
  artifact_name:
    description: 'Name of the MLA-05 evidence artifact'
    value: ${{ steps.evaluate.outputs.artifact_name }}
  artifact_path:
    description: 'Path to the MLA-05 evidence artifact zip file'
    value: ${{ steps.evaluate.outputs.artifact_path }}
  evidence_dir:
    description: 'Path to the evidence directory'
    value: ${{ steps.evaluate.outputs.evidence_dir }}
  summary:
    description: 'Markdown summary of evaluation results'
    value: ${{ steps.evaluate.outputs.summary }}
  # CNA-01 outputs
  cna01_status:
    description: 'KSI-CNA-01 status: PASS, FAIL, or ERROR'
    value: ${{ steps.evaluate.outputs.cna01_status }}
  cna01_artifact_name:
    description: 'Name of the CNA-01 evidence artifact'
    value: ${{ steps.evaluate.outputs.cna01_artifact_name }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Terraform
      if: inputs.terraform_version != ''
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Verify Terraform installation
      shell: bash
      run: |
        if command -v terraform &> /dev/null; then
          echo "Terraform version: $(terraform version -json | jq -r .terraform_version)"
        else
          echo "::warning::Terraform not found in PATH. MLA05-B evaluation will fail."
        fi

    - name: Install Python dependencies
      shell: bash
      run: |
        pip install python-hcl2>=4.3.0 pydantic>=2.5.0

    - name: Run KSI evaluation
      id: evaluate
      shell: bash
      env:
        INPUT_ROOT_PATHS: ${{ inputs.root_paths }}
        PYTHONPATH: ${{ github.action_path }}
      run: |
        python ${{ github.action_path }}/action/src/main.py

    - name: Upload MLA-05 evidence artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.evaluate.outputs.artifact_name }}
        path: |
          ${{ github.workspace }}/.fedramp-evidence/evidence/ksi-mla-05/
        retention-days: 90
        if-no-files-found: error

    - name: Upload CNA-01 evidence artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.evaluate.outputs.cna01_artifact_name }}
        path: |
          ${{ github.workspace }}/.fedramp-evidence/evidence/ksi-cna-01/
        retention-days: 90
        if-no-files-found: error

    - name: Upload results summary
      uses: actions/upload-artifact@v4
      with:
        name: fedramp-ksi-results
        path: ${{ github.workspace }}/.fedramp-evidence/results.json
        retention-days: 90
        if-no-files-found: warn
